
sudo: required

services:
- docker

env:
- DOCKER_COMPOSE_VERSION=1.4.2

language: bash

before_install:
##get latest docker-ce version
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- docker --version
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose --version

# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

# build image: telegraf
- cd $TRAVIS_BUILD_DIR/telegraf
- docker build -t stelzer77/telegraf-armhf .

- cd $TRAVIS_BUILD_DIR/influxdb
- docker build -t stelzer77/influxdb-armhf .

- cd $TRAVIS_BUILD_DIR/kapacitor
- docker build -t stelzer77/kapacitor-armhf .

- cd $TRAVIS_BUILD_DIR/chronograf
- docker build -t stelzer77/chronograf-armhf .

- cd $TRAVIS_BUILD_DIR
# test image
# TODO

after_success:
# push image if from master branch
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";

    TELEGRAF_TAG=$(grep "ENV TELEGRAF_VERSION" telegraf/Dockerfile | awk 'NF>1{print $NF}');
    docker tag stelzer77/telegraf-armhf:latest stelzer77/telegraf-armhf:$TELEGRAF_TAG;
    docker push stelzer77/telegraf-armhf:latest;
    docker push stelzer77/telegraf-armhf:$TELEGRAF_TAG;

    INFLUX_DB_TAG=$(grep "ENV INFLUX_DB_VERSION" influxdb/Dockerfile | awk 'NF>1{print $NF}');
    docker tag stelzer77/influxdb-armhf:latest stelzer77/influxdb-armhf:$INFLUX_DB_TAG;
    docker push stelzer77/influxdb-armhf:latest;
    docker push stelzer77/influxdb-armhf:$INFLUX_DB_TAG;

    CHRONOGRAF_TAG=$(grep "ENV CHRONOGRAF_VERSION" chronograf/Dockerfile | awk 'NF>1{print $NF}');
    docker tag stelzer77/chronograf-armhf:latest stelzer77/chronograf-armhf:$CHRONOGRAF_TAG;
    docker push stelzer77/chronograf-armhf:latest;
    docker push stelzer77/chronograf-armhf:$CHRONOGRAF_TAG;

    KAPACITOR_TAG=$(grep "ENV KAPACITOR_VERSION" kapacitor/Dockerfile | awk 'NF>1{print $NF}');
    docker tag stelzer77/kapacitor-armhf:latest stelzer77/kapacitor-armhf:$KAPACITOR_TAG;
    docker push stelzer77/kapacitor-armhf:latest;
    docker push stelzer77/kapacitor-armhf:$KAPACITOR_TAG;

  fi

