sudo: required

services:
- docker

language: bash

script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t stelzer77/telegraf-armhf telegraf/
# test image
- docker run stelzer77/telegraf-armhf config
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV TELEGRAF_VERSION" telegraf-armhf/Dockerfile | awk 'NF>1{print $NF}')
    docker tag stelzer77/telegraf-armhf stelzer77/telegraf-armhf:$TAG
    docker push stelzer77/telegraf-armhf:$TAG
    docker push stelzer77/telegraf-armhf
  fi
