version: "3"

services:

  #Influx-DB service
  influxdb:
    image: stelzer77/influxdb-armhf
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"

  #Telegraf service
  telegraf:
    image: stelzer77/telegraf-armhf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - MQTT_SERVER_IP=192.168.178.153:1883
    links:
      - influxdb:influxdb
    depends_on:
      - influxdb

  #Kapacitor service
  kapacitor:
    image: stelzer77/kapacitor-armhf
    volumes:
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
#      - kapacitor-data:/var/lib/kapacitor
    ports:
      - "9092:9092"
    links:
      - influxdb:influxdb
    depends_on:
      - influxdb

  #Chronograf service
  chronograf:
    image: stelzer77/chronograf-armhf
    volumes:
      - chronograf-data:/var/lib/chronograf
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - KAPACITOR_URL=http://kapacitor:9092
    links:
      - influxdb:influxdb
    depends_on:
      - influxdb


  #Grafana service
  grafana:
    image: fg2it/grafana-armhf:v4.4.3
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
      - influxdb:influxdb
    depends_on:
      - influxdb

volumes:
  influxdb-data:
    external:
      name: influxdb-data-volume
  grafana-data:
    external:
      name: grafana-data-volume
  kapacitor-data:
    external:
      name: kapacitor-data-volume
  chronograf-data:
    external:
      name: chronograf-data-volume
  log-data:
    external:
      name: log-data-volume
