version: "3"

services:

#Influx-DB service
  influxdb:
    image: stelzer77/influxdb-armhf
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"
  
#Telegraf service
  telegraf:
    image: stelzer77/telegraf-armhf
    volumes:
      - ./telegraf.config:/etc/telegraf/telegraf.config:ro
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    links:
      - influxdb:influxdb

#Grafana service
  grafana:
    image: fg2it/grafana-armhf:v4.4.3
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb:influxdb
    depends_on:
      - influxdb

volumes:
  influxdb-data:
    external:
      name: influxdb-data-volume
  grafana-data:
    external:
      name: grafana-data-volume
